# cards.py
from dataclasses import dataclass

@dataclass
class Card:
    name: str
    image: str

cards = [
    Card("Numero 1: Cancello Numeron Ekam", 								"images/numbers/1.png"),
    Card("Numero 1: Infezione Buzzking", 									"images/numbers/1B.png"),
    Card("Numero 2: Cancello Numeron Dve", 									"images/numbers/2.png"),
    Card("Numero 2: Zanzara Ninja dell'Ombra", 								"images/numbers/2B.png"),
    Card("Numero 3: Cancello Numeron Trini", 								"images/numbers/3.png"),
    Card("Numero 3: Re Cicala", 											"images/numbers/3B.png"),
    Card("Numero 4: Cancello Numeron Catvari", 								"images/numbers/4.png"),
    Card("Numero 4: Kraken Furtivo", 										"images/numbers/4B.png"),
    Card("Numero 5: Drago Chimera del Destino", 							"images/numbers/5.png"),
    Card("Numero 6: Cronomalia Atlandis", 									"images/numbers/6.png"),
    Card("Numero 7: Sequenza Fortunata", 									"images/numbers/7.png"),
    Card("Numero 8: Re Araldico Genoma-Eredità", 							"images/numbers/8.png"),
    Card("Numero 9: Sfera Dyson", 											"images/numbers/9.png"),
    Card("Numero 10: Illuminocavaliere", 									"images/numbers/10.png"),
    Card("Numero 11: Grande Occhio", 										"images/numbers/11.png"),
    Card("Numero 12: Ninja Armatura di Ombra Scarlatta", 					"images/numbers/12.png"),
    Card("Numero 13: Personificazione del Crimine", 						"images/numbers/13.png"),
    Card("Numero 14: Sarameya Avido", 										"images/numbers/14.png"),
    Card("Numero 15: Burattino Arnese Macinatore Gigante", 					"images/numbers/15.png"),
    Card("Numero 16: Maestro Shock", 										"images/numbers/16.png"),
    Card("Numero 17: Drago Leviatano", 										"images/numbers/17.png"),
    Card("Numero 18: Patriarca dell'Araldo", 								"images/numbers/18.png"),
    Card("Numero 19: Freezadonte", 											"images/numbers/19.png"),
    Card("Numero 20: Giga-Brillante", 										"images/numbers/20.png"),
    Card("Numero 21: Signora Giustizia Congelata", 							"images/numbers/21.png"),
    Card("Numero 22: Zombiestein", 											"images/numbers/22.png"),
    Card("Numero 23: Lancillotto, Oscuro Cavaliere del Mondo Sotterraneo", 	"images/numbers/23.png"),
    Card("Numero 24: Dragulas il Drago Vampyre", 							"images/numbers/24.png"),
    Card("Numero 25: Focus Forza", 											"images/numbers/25.png"),
    Card("Numero 26: Rotta Spaziale Polpodeviazione", 						"images/numbers/26.png"),
    Card("Numero 27: Corazzata Corazzanoid", 								"images/numbers/27.png"),
    Card("Numero 28: Falena Titanica", 										"images/numbers/28.png"),
    Card("Numero 29: Gatta Manichino", 										"images/numbers/29.png"),
    Card("Numero 30: Golem Acido della Distruzione", 						"images/numbers/30.png"),
    Card("Numero 31: Personificazione della Punizione", 					"images/numbers/31.png"),
    Card("Numero 32: Draghetto Squalo", 									"images/numbers/32.png"),
    Card("Numero 33: Cronomalia Machu Mech", 								"images/numbers/33.png"),
    Card("Numero 34: Terror-Byte", 											"images/numbers/34.png"),
    Card("Numero 35: Tarantola Famelica", 									"images/numbers/35.png"),
    Card("Numero 36: Cronomalia Chateau Huyuk", 							"images/numbers/36.png"),
    Card("Numero 37: Drago Ragno Squalo Intessuto di Speranza", 			"images/numbers/37.png"),
    Card("Numero 38: Drago Titanico Galattico Annunciatore di Speranza", 	"images/numbers/38.png"),
    Card("Numero 39: Doppia Utopia", 										"images/numbers/39D.png"),
    Card("Numero 39: Oltre l'Utopia", 										"images/numbers/39B.png"),
    Card("Numero 39: Radici dell'Utopia", 									"images/numbers/39C.png"),
    Card("Numero 39: Utopia", 												"images/numbers/39.png"),
    Card("Numero 39: Utopia Ascendente", 									"images/numbers/39E.png"),
    Card("Numero 40: Burattino Arnese delle Corde", 						"images/numbers/40.png"),
    Card("Numero 41: Bagooska il Tapiro Terribilmente Stanco", 				"images/numbers/41.png"),
    Card("Numero 42: Tomahawk Galattico", 									"images/numbers/42.png"),
    Card("Numero 43: Manipolatore di Anime", 								"images/numbers/43.png"),
    Card("Numero 44: Pegaso del Cielo", 									"images/numbers/44.png"),
    Card("Numero 45: Logos Sbriciolante il Profeta della Demolizione", 		"images/numbers/45.png"),
    Card("Numero 46: Dragluone", 											"images/numbers/46.png"),
    Card("Numero 47: Squalo Incubo", 										"images/numbers/47.png"),
    Card("Numero 48: Lich Ombra", 											"images/numbers/48.png"),
    Card("Numero 49: Sintonia della Fortuna", 								"images/numbers/49.png"),
    Card("Numero 50: Navenera di Corn", 									"images/numbers/50.png"),
    Card("Numero 51: Finitore Braccio Forte", 								"images/numbers/51.png"),
    Card("Numero 52: Re Granchio Diamante", 								"images/numbers/52.png"),
    Card("Numero 53: Heart-eartH", 											"images/numbers/53.png"),
    Card("Numero 54: Cuore di Leone", 										"images/numbers/54.png"),
    Card("Numero 55: Golia Gogogo", 										"images/numbers/55.png"),
    Card("Numero 56: Ratto d'Oro", 											"images/numbers/56.png"),
    Card("Numero 57: Drago Polvere Tricefalo", 								"images/numbers/57.png"),
    Card("Numero 58: Visore Ardente", 										"images/numbers/58.png"),
    Card("Numero 59: Cuoco Corrotto", 										"images/numbers/59.png"),
    Card("Numero 60: Dugares il Senzatempo", 								"images/numbers/60.png"),
    Card("Numero 61: Volcasauro", 											"images/numbers/61.png"),
    Card("Numero 62: Drago Fotonico Primordiale Occhi Galattici", 			"images/numbers/62.png"),
    Card("Numero 63: Soldato Shamoji", 										"images/numbers/63.png"),
    Card("Numero 64: Procione Ronin Sandayu", 								"images/numbers/64.png"),
    Card("Numero 65: Combattente Djinn", 									"images/numbers/65.png"),
    Card("Numero 66: Scarabeo Maestro delle Chiavi", 						"images/numbers/66.png"),
    Card("Numero 67: Distruttore Appaiadadi", 								"images/numbers/67.png"),
    Card("Numero 68: Sanaphond la Prigione del Cielo", 						"images/numbers/68.png"),
    Card("Numero 69: Cimiero dell'Araldo - Demolizione Materia Oscura", 	"images/numbers/69C.png"),
    Card("Numero 69: Cimiero dell'Araldo - Flusso Frantumante", 			"images/numbers/69B.png"),
    Card("Numero 69: Cimiero dell'Araldo", 									"images/numbers/69.png"),
    Card("Numero 70: Peccato Malevolo", 									"images/numbers/70.png"),
    Card("Numero 71: Squalo Rebarian", 										"images/numbers/71.png"),
    Card("Numero 72: Torre Shogi", 											"images/numbers/72.png"),
    Card("Numero 73: Spruzzo dell'Abisso", 									"images/numbers/73.png"),
    Card("Numero 74: Maestro delle Lame", 									"images/numbers/74.png"),
    Card("Numero 75: Ombra Sussurri Ingannatori", 							"images/numbers/75.png"),
    Card("Numero 76: Gradielle l'Armonizzatrice", 							"images/numbers/76.png"),
    Card("Numero 77: I Sette Peccati", 										"images/numbers/77.png"),
    Card("Numero 78: Archivio dei Numeri", 									"images/numbers/78.png"),
    Card("Numero 79: Pugile Indomito Nova Kaiser", 							"images/numbers/79.png"),
    Card("Numero 80: Rapsodia in Berserk", 									"images/numbers/80.png"),
    Card("Numero 81: Cannone Ferroviario Supercorazzato Super Dora", 		"images/numbers/81.png"),
    Card("Numero 82: Cuoreterrenodraco", 									"images/numbers/82.png"),
    Card("Numero 83: Regina Galattica", 									"images/numbers/83.png"),
    Card("Numero 84: Acquisitore di Dolore", 								"images/numbers/84.png"),
    Card("Numero 85: Scatola Pazza", 										"images/numbers/85.png"),
    Card("Numero 86: Campione Eroico - Rhongomyniad", 						"images/numbers/86.png"),
    Card("Numero 87: Regina della Notte", 									"images/numbers/87.png"),
    Card("Numero 88: Burattino Arnese del Leone", 							"images/numbers/88.png"),
    Card("Numero 89: Diablosis l'Hacker di Menti", 							"images/numbers/89.png"),
    Card("Numero 90: Signore Fotonico Occhi Galattici", 					"images/numbers/90.png"),
    Card("Numero 91: Drago Tuono Scintilla", 								"images/numbers/91.png"),
    Card("Numero 92: Drago Heart-eartH", 									"images/numbers/92.png"),
    Card("Numero 93: Kaiser Utopia", 										"images/numbers/93.png"),
    Card("Numero 94: Crystalzero", 											"images/numbers/94.png"),
    Card("Numero 95: Drago Materia Oscura Occhi Galattici", 				"images/numbers/95.png"),
    Card("Numero 96: Nebbia Oscura", 										"images/numbers/96.png"),
    Card("Numero 97: Draglubione", 											"images/numbers/97.png"),
    Card("Numero 98: Antitopiano", 											"images/numbers/98.png"),
    Card("Numero 99: Drago Utopico", 										"images/numbers/99.png"),
    Card("Numero 99: Dragonar Utopia", 										"images/numbers/99B.png"),
    Card("Numero 100: Drago Numeron", 										"images/numbers/100.png"),
    Card("Numero 101: ARCA Onore Silente", 									"images/numbers/101.png"),
    Card("Numero 102: Sentinella Serafino delle Stelle", 					"images/numbers/102.png"),
    Card("Numero 103: Ragnazero", 											"images/numbers/103.png"),
    Card("Numero 104: Masquerade", 											"images/numbers/104.png"),
    Card("Numero 105: Pugile Indomito Star Cestus", 						"images/numbers/105.png"),
    Card("Numero 106: Mano Gigante", 										"images/numbers/106.png"),
    Card("Numero 107: Drago Tachionico Occhi Galattici", 					"images/numbers/107.png"),
    Card("Numero C1: Cancello del Chaos Numeron Sunya", 					"images/numbers/C1.png"),
    Card("Numero C5: Drago Chimera del Chaos", 								"images/numbers/C5.png"),
    Card("Numero C6: Cronomalia Chaos Atlandis", 							"images/numbers/C6.png"),
    Card("Numero C9: Sfera Dyson del Chaos", 								"images/numbers/C9.png"),
    Card("Numero C15: Burattino Arnese Cacciatore Gigante", 				"images/numbers/C15.png"),
    Card("Numero C32: Draghetto Squalo LeVeiss", 							"images/numbers/C32B.png"),
    Card("Numero C32: Draghetto Squalo Veiss", 								"images/numbers/C32.png"),
    Card("Numero C39: Raggio Utopia", 										"images/numbers/C39.png"),
    Card("Numero C39: Raggio Utopia V", 									"images/numbers/C39B.png"),
    Card("Numero C39: Raggio Utopia Vittoria", 								"images/numbers/C39C.png"),
    Card("Numero C40: Burattino Arnese delle Corde Oscure", 				"images/numbers/C40.png"),
    Card("Numero C43: Alto Manipolatore del Chaos", 						"images/numbers/C43.png"),
    Card("Numero C62: Neo Drago Fotonico Primordiale Occhi Galattici", 		"images/numbers/C62.png"),
    Card("Numero C65: Re Overdemone", 										"images/numbers/C65.png"),
    Card("Numero C69: Cimiero dell'Araldo dell'Orrore", 					"images/numbers/C69.png"),
    Card("Numero C73: Super Spruzzo dell'Abisso", 							"images/numbers/C73.png"),
    Card("Numero C79: Pugile Indomito Generale Kaiser", 					"images/numbers/C79.png"),
    Card("Numero C80: Requiem in Berserk", 									"images/numbers/C80.png"),
    Card("Numero C88: Burattino Arnese del Leone Disastro", 				"images/numbers/C88.png"),
    Card("Numero C92: Drago del Chaos Heart-eartH", 						"images/numbers/C92.png"),
    Card("Numero C96: Tempesta Oscura", 									"images/numbers/C96.png"),
    Card("Numero C101: OSCURITÀ Onore Silente", 							"images/numbers/C101.png"),
    Card("Numero C102: Arcidemone Serafino", 								"images/numbers/C102.png"),
    Card("Numero C103: Ragnainfinito", 										"images/numbers/C103.png"),
    Card("Numero C104: Masquerade Orrore Umbral", 							"images/numbers/C104.png"),
    Card("Numero C105: Pugile Indomito Comet Cestus", 						"images/numbers/C105.png"),
    Card("Numero C106: Mano Gigante Rossa", 								"images/numbers/C106.png"),
    Card("Numero C107: Neo Drago Tachionico Occhi Galattici", 				"images/numbers/C107.png"),
    Card("Numero C1000: Numerounius", 										"images/numbers/C1000.png"),
    Card("Numero F0: Futuro Utopico", 										"images/numbers/F0.png"),
    Card("Numero F0: Futuro Utopico Colpo", 								"images/numbers/F0B.png"),
    Card("Numero F0: Futuro Utopico Zexal", 								"images/numbers/F0C.png"),
    Card("Numero F0: Futuro Draco Utopico", 								"images/numbers/F0D.png"),
    Card("Numero S0: ZEXAL Utopico", 										"images/numbers/S0.png"),
    Card("Numero S37: Ragno Squalo", 										"images/numbers/S37.png"),
    Card("Numero S38: Galassia Titanica", 									"images/numbers/S38.png"),
    Card("Numero S39: Utopia Prime", 										"images/numbers/S39.png"),
    Card("Numero S39: Utopia il Fulmine", 									"images/numbers/S39B.png"),
    Card("Numero XX: Infinità Oscura Utopica", 								"images/numbers/XX.png"),
    Card("Numero iC1000: Numerounius Numerounia", 							"images/numbers/iC1000.png"),
]
